### ISSUE TITLE
Database optimalizations

### ISSUE THREAD

**Issue by DeStilleGast** [CFCorp/CFsAPI#11]
I have noticed you save a hardcoded url like example `https://cdn.computerfreaker.cf/random.png`

Also the doctrine database doesnt get used verry well, you should try to make a entity that contains the type and filename. (or if you want 1 entity per type)

it could if you migrate the database to this you should be able to easy edit the url/domain if you ever change it from `computerfreaker.cf` to like `cfmaster.com`. If you keep it like this, your database/api will be down and a pain in the ass to change everything.

**Comment by eissternchen-Leni** [comment]
Yeah good idea

**Comment by CFTheMaster** [comment]
![image](https://user-images.githubusercontent.com/22801402/47620749-083bab80-daee-11e8-96c9-09fad0cf62f9.png)
entities like these ones?

**Comment by DeStilleGast** [comment]
Yes

**Comment by CFTheMaster** [comment]
alright gonna look into it how to use Entities :+1:

**Comment by CFTheMaster** [comment]
your other issue has been implemented but not pushed just yet :+1:

**Comment by CFTheMaster** [comment]
has been fixed as of latest push
